from locales import Step
import shutil
import os
from subprocess import Popen
class Reversal():
    REVERSAL_TEXT = { 
        0: {
        'es': 'Ha clickeado cerrar esta accion no puede deshacerse si continua el juego puede quedar inoperable y que deba descargarlo nuevamente',
        'en': 'You have clicked close this action can not be undone if you continue the game may become inoperable and you must download it again',
        'fr': 'Vous avez cliqué sur fermer cette action ne peut pas être annulée si vous continuez le jeu peut devenir inopérable et vous devez le télécharger à nouveau',
        'de': 'Sie haben auf Schließen geklickt. Diese Aktion kann nicht rückgängig gemacht werden. Wenn Sie das Spiel fortsetzen, wird es möglicherweise nicht mehr ausgeführt und Sie müssen es erneut herunterladen',
        'it': 'Hai cliccato su chiudi questa azione non può essere annullata se continui il gioco potrebbe diventare inoperabile e dovresti scaricarlo di nuovo',
        'pt': 'Você clicou em fechar esta ação não pode ser desfeita se você continuar o jogo pode se tornar inoperante e você deve baixá-lo novamente',
        'ru': 'Вы нажали кнопку закрыть, это действие нельзя отменить, если вы продолжите игру, она может стать неоперабельной, и вам придется снова ее загрузить',
        'ja': '閉じるをクリックしました。このアクションは元に戻すことはできません。ゲームを続行すると、ゲームが動作しなくなり、再度ダウンロードする必要があります',
        'zh': '您单击了关闭此操作无法撤消，如果您继续游戏可能会变得无法操作，您必须重新下载它',
        'ko': '이 작업을 취소 할 수 없습니다. 게임을 계속하면 게임이 작동하지 않게되어 다시 다운로드해야합니다.',
        'ar': 'لقد نقرت على إغلاق هذا الإجراء لا يمكن التراجع عنه إذا استمرت اللعبة قد تصبح غير قابلة للتشغيل ويجب عليك تنزيلها مرة أخرى',
        'tr': 'Kapat\'ı tıkladınız. Bu işlem geri alınamaz. Oyunu devam ettirirseniz, oyun işlevsiz hale gelebilir ve yeniden indirmeniz gerekir',
        'pl': 'Kliknąłeś zamknij, tej akcji nie można cofnąć, jeśli będziesz kontynuować grę, może stać się nieoperacyjna i będziesz musiał ją ponownie pobrać',
        'uk': 'Ви натиснули кнопку закрити, ця дія не може бути скасована, якщо ви продовжите гру, вона може стати неоперабельною, і вам доведеться знову її завантажити',
        'ro': 'Ați făcut clic pe închidere, această acțiune nu poate fi anulată dacă continuați jocul poate deveni inoperabil și trebuie să îl descărcați din nou',
        'hu': 'Bezárásra kattintott. Ez a művelet nem vonható vissza. Ha folytatja a játékot, akkor az inoperatívá válhat, és újra letöltheti',
        'cs': 'Klikli jste na zavření, tuto akci nelze vrátit zpět, pokud budete pokračovat ve hře, může se stát neoperabilní a budete ji muset znovu stáhnout',
        'sv': 'Du har klickat på stänga den här åtgärden kan inte ångras om du fortsätter kan spelet bli inoperativt och du måste ladda ner det igen',
        'nl': 'Je hebt geklikt op sluiten deze actie kan niet ongedaan worden gemaakt als je doorgaat kan het spel onbruikbaar worden en moet je het opnieuw downloaden',
        'bg': 'Натиснахте затваряне, това действие не може да бъде отменено, ако продължите играта може да стане неработоспособна и трябва да я изтеглите отново',
        'fi': 'Olet napsauttanut sulje tämä toiminto ei voi peruuttaa, jos jatkat peliä voi tulla toimintakyvyttömäksi ja sinun on ladattava se uudelleen',
        'da': 'Du har klikket luk denne handling kan ikke fortrydes, hvis du fortsætter kan spillet blive inoperativt, og du skal downloade det igen',
        'no': 'Du har klikket lukk denne handlingen kan ikke angres hvis du fortsetter kan spillet bli inoperativt og du må laste det ned igjen',
        'el': 'Έχετε κάνει κλικ στο κλείσιμο αυτής της ενέργειας δεν μπορεί να αναιρεθεί αν συνεχίσετε το παιχνίδι μπορεί να γίνει ανενεργό και πρέπει να το κατεβάσετε ξανά',
        'he': 'לחצת על סגור פעולה זו אינה ניתנת לביטול אם תמשיך המשחק עשוי להיות לא פעיל ועליך להוריד אותו שוב',
        }, 
        1: {
            'es': 'Ha clickeado cerrar el ejecutable intentara reversar los cambios realizados hasta el momento. Se mantendra la version actual y el juego no será actualizado',
            'en': 'You have clicked close the executable will try to reverse the changes made so far. The current version will be maintained and the game will not be updated',
            'fr': 'Vous avez cliqué sur fermer l\'exécutable tentera d\'annuler les modifications apportées jusqu\'à présent. La version actuelle sera conservée et le jeu ne sera pas mis à jour',
            'de': 'Sie haben auf Schließen geklickt. Die ausführbare Datei versucht, die bisher vorgenommenen Änderungen rückgängig zu machen. Die aktuelle Version wird beibehalten und das Spiel wird nicht aktualisiert',
            'it': 'Hai cliccato su chiudi l\'eseguibile cercherà di annullare le modifiche apportate finora. La versione corrente verrà mantenuta e il gioco non verrà aggiornato',
            'pt': 'Você clicou em fechar o executável tentará reverter as alterações feitas até agora. A versão atual será mantida e o jogo não será atualizado',
            'ru': 'Вы нажали кнопку закрыть, исполняемый файл попытается отменить внесенные изменения. Текущая версия будет сохранена, а игра не будет обновлена',
            'ja': '実行可能ファイルを閉じるをクリックしました。これまでに行われた変更を元に戻そうとします。現在のバージョンは維持され、ゲームは更新されません',
            'zh': '您单击了关闭可执行文件将尝试撤消到目前为止所做的更改。将保留当前版本，游戏将不会更新',
            'ko': '실행 파일을 닫기를 클릭했습니다. 지금까지 한 변경 사항을 취소하려고합니다. 현재 버전이 유지되고 게임이 업데이트되지 않습니다',
            'ar': 'لقد نقرت على إغلاق الملف القابل للتنفيذ سيحاول عكس التغييرات التي تم إجراؤها حتى الآن. سيتم الاحتفاظ بالإصدار الحالي ولن يتم تحديث اللعبة',
            'tr': 'Yürütülebilir dosyayı kapat\'a tıkladınız. Şu ana kadar yapılan değişiklikleri geri almaya çalışacak. Mevcut sürüm korunacak ve oyun güncellenmeyecek',
            'pl': 'Kliknąłeś zamknij plik wykonywalny spróbuje cofnąć zmiany dokonane do tej pory. Obecna wersja zostanie zachowana, a gra nie zostanie zaktualizowana',
            'uk': 'Ви натиснули кнопку закрити, виконуваний файл спробує скасувати внесені зміни. Поточна версія буде збережена, а гра не буде оновлена',
            'ro': 'Ați făcut clic pe închidere, executabilul va încerca să revină la modificările făcute până acum. Versiunea curentă va fi păstrată și jocul nu va fi actualizat',
            'hu': 'Kattintson a bezárásra a végrehajtható megpróbálja visszafordítani a változtatásokat eddig. A jelenlegi verzió megmarad, és a játék nem frissül',
            'cs': 'Klikli jste na zavření spustitelný se pokusí vrátit změny provedené dosud. Aktuální verze bude zachována a hra nebude aktualizována',
            'sv': 'Du har klickat på stänga den körbara kommer att försöka vända de hittills gjorda ändringarna. Den aktuella versionen kommer att behållas och spelet kommer inte att uppdateras',
            'nl': 'Je hebt geklikt op sluiten de uitvoerbare zal proberen de tot nu toe aangebrachte wijzigingen ongedaan te maken. De huidige versie wordt behouden en het spel wordt niet bijgewerkt',
            'bg': 'Натиснахте затваряне, изпълнимият файл ще се опита да обърне промените, направени до момента. Текущата версия ще бъде запазена, а играта няма да бъде актуализирана',
            'fi': 'Olet napsauttanut sulje suoritettava yrittää kääntää muutokset tähän mennessä. Nykyinen versio säilyy ja peliä ei päivitetä',
            'da': 'Du har klikket lukke den eksekverbare vil forsøge at vende de hidtil foretagne ændringer. Den aktuelle version vil blive opretholdt, og spillet vil ikke blive opdateret',
            'no': 'Du har klikket lukk den kjørbare vil prøve å reversere endringene som er gjort så langt. Gjeldende versjon vil bli opprettholdt og spillet vil ikke bli oppdatert',
            'el': 'Έχετε κάνει κλικ στο κλείσιμο του εκτελέσιμου θα προσπαθήσει να αναστρέψει τις αλλαγές που έχουν γίνει μέχρι στιγμής. Η τρέχουσα έκδοση θα διατηρηθεί και το παιχνίδι δεν θα ενημερωθεί',
            'he': 'לחצת על סגור הקובץ הניתן להרצה ינסה להיפך את השינויים שבוצעו עד כה. הגרסה הנוכחית תישמר והמשחק לא יתעדכן',
        }, 
        2: {
            'es': 'Ha clickeado cerrar esta accion no puede deshacerse. El juego ya ha sido actualizado, pero si cancela los procesos restantes, es posible que queden inconsistencias, en los archivos.',
            'en': 'You have clicked close this action can not be undone. The game has already been updated, but if you cancel the remaining processes, inconsistencies may remain in the files.',
            'fr': 'Vous avez cliqué sur fermer cette action ne peut pas être annulée. Le jeu a déjà été mis à jour, mais si vous annulez les processus restants, des incohérences peuvent subsister dans les fichiers.',
            'de': 'Sie haben auf Schließen geklickt. Diese Aktion kann nicht rückgängig gemacht werden. Das Spiel wurde bereits aktualisiert, aber wenn Sie die verbleibenden Prozesse abbrechen, können Inkonsistenzen in den Dateien verbleiben.',
            'it': 'Hai cliccato su chiudi questa azione non può essere annullata. Il gioco è già stato aggiornato, ma se annulli i processi rimanenti, potrebbero rimanere delle incongruenze nei file.',
            'pt': 'Você clicou em fechar esta ação não pode ser desfeita. O jogo já foi atualizado, mas se você cancelar os processos restantes, inconsistências podem permanecer nos arquivos.',
            'ru': 'Вы нажали кнопку закрыть, это действие нельзя отменить. Игра уже была обновлена, но если вы отмените оставшиеся процессы, в файлах могут остаться несоответствия.',
            'ja': '閉じるをクリックしました。このアクションは元に戻すことはできません。ゲームはすでに更新されていますが、残りのプロセスをキャンセルすると、ファイルに不整合が残る場合があります。',
            'zh': '您单击了关闭此操作无法撤消。游戏已经更新，但是如果您取消剩余的进程，则文件中可能会存在不一致。',
            'ko': '이 작업을 취소 할 수 없습니다. 게임은 이미 업데이트되었지만 남은 프로세스를 취소하면 파일에 불일치가 남을 수 있습니다.',
            'ar': 'لقد نقرت على إغلاق هذا الإجراء لا يمكن التراجع عنه. تم تحديث اللعبة بالفعل ، ولكن إذا قمت بإلغاء العمليات المتبقية ، فقد تبقى عدم التطابق في الملفات.',
            'tr': 'Kapat\'ı tıkladınız. Bu işlem geri alınamaz. Oyun zaten güncellendi, ancak kalan işlemleri iptal ederseniz dosyalarda tutarsızlıklar kalabilir.',
            'pl': 'Kliknąłeś zamknij, tej akcji nie można cofnąć. Gra została już zaktualizowana, ale jeśli anulujesz pozostałe procesy, w plikach mogą pozostać niezgodności.',
            'uk': 'Ви натиснули кнопку закрити, ця дія не може бути скасована. Гра вже була оновлена, але якщо ви скасуєте залишкові процеси, в файлах можуть залишитися несоответствия.',
            'ro': 'Ați făcut clic pe închidere, această acțiune nu poate fi anulată. Jocul a fost deja actualizat, dar dacă anulați procesele rămase, pot rămâne inconsistente în fișiere.',
            'hu': 'Bezárásra kattintott. Ez a művelet nem vonható vissza. A játék már frissült, de ha megszakítja a fennmaradó folyamatokat, inkonzisztenciák maradhatnak a fájlokban.',
            'cs': 'Klikli jste na zavření, tuto akci nelze vrátit zpět. Hra již byla aktualizována, ale pokud zrušíte zbývající procesy, mohou v souborech zůstat nekonzistence.',
            'nl': 'Je hebt geklikt op sluiten deze actie kan niet ongedaan worden gemaakt. Het spel is al bijgewerkt, maar als u de resterende processen annuleert, kunnen inconsistenties in de bestanden achterblijven.',
            'bg': 'Натиснахте затваряне, това действие не може да бъде отменено. Играта вече е актуализирана, но ако отмените останалите процеси, във файловете може да останат несъответствия.',
            'fi': 'Olet napsauttanut sulje tätä toimintoa ei voi peruuttaa. Peli on jo päivitetty, mutta jos peruutat jäljellä olevat prosessit, tiedostoissa voi olla ristiriitaisuuksia.',
        },
        3: {
            'en': ("Can't close while extracting", "The aplication can't close until extracting is finished, as soon as it finished this window will close and the extracted folder will be deleted"),
            'es': ("No se puede cerrar mientras se extrae", "La aplicación no puede cerrarse hasta que se termine de extraer, en cuanto termine esta ventana se cerrará y la carpeta extraida será eliminada"),
            'fr': ("Impossible de fermer pendant l'extraction", "L'application ne peut pas être fermée tant que l'extraction n'est pas terminée, dès qu'elle est terminée, cette fenêtre se fermera et le dossier extrait sera supprimé"),
            'de': ("Kann nicht schließen, während extrahiert wird", "Die Anwendung kann nicht geschlossen werden, bis die Extraktion abgeschlossen ist. Sobald sie abgeschlossen ist, wird dieses Fenster geschlossen und der extrahierte Ordner wird gelöscht"),
            'it': ("Impossibile chiudere durante l'estrazione", "L'applicazione non può essere chiusa fino a quando l'estrazione non è terminata, non appena è terminata questa finestra verrà chiusa e la cartella estratta verrà eliminata"),
            'pt': ("Não é possível fechar durante a extração", "O aplicativo não pode ser fechado até que a extração seja concluída, assim que for concluído, esta janela será fechada e a pasta extraída será excluída"),
            'ru': ("Невозможно закрыть во время извлечения", "Приложение не может быть закрыто, пока извлечение не будет завершено, как только оно будет завершено, это окно будет закрыто, а извлеченная папка будет удалена"),
            'ja': ("抽出中に閉じることはできません", "抽出が完了するまでアプリケーションを閉じることはできません。抽出が完了すると、このウィンドウが閉じられ、抽出されたフォルダが削除されます"),
            'zh': ("无法在提取时关闭", "无法在提取完成之前关闭应用程序，一旦完成，此窗口将关闭并删除提取的文件夹"),
            'ko': ("추출 중에는 닫을 수 없습니다", "추출이 완료 될 때까지 응용 프로그램을 닫을 수 없습니다. 추출이 완료되면이 창이 닫히고 추출 된 폴더가 삭제됩니다"),
            'ar': ("لا يمكن الإغلاق أثناء الاستخراج", "لا يمكن إغلاق التطبيق حتى يتم الانتهاء من الاستخراج ، بمجرد الانتهاء منه ، سيتم إغلاق هذه النافذة وسيتم حذف المجلد المستخرج"),
            'tr': ("Çıkarılırken kapatılamıyor", "Çıkarılana kadar uygulama kapatılamaz, çıkarılması bittiğinde bu pencere kapatılacak ve çıkarılan klasör silinecek"),
            'pl': ("Nie można zamknąć podczas wypakowywania", "Aplikacja nie może zostać zamknięta, dopóki wypakowywanie nie zostanie zakończone, gdy tylko zostanie zakończone, to okno zostanie zamknięte, a wypakowany folder zostanie usunięty"),
            'uk': ("Не вдається закрити під час вилучення", "Додаток не може бути закритий, поки триває вилучення, як тільки воно буде завершено, це вікно буде закрите, а вилучена папка буде видалена"),
            'ro': ("Nu se poate închide în timpul extragerii", "Aplicația nu poate fi închisă până când extragerea nu este terminată, imediat ce este terminată, această fereastră se va închide și folderul extras va fi șters"),
            'hu': ("Nem lehet bezárni a kicsomagolás közben", "A kicsomagolás befejezéséig nem lehet bezárni az alkalmazást, amint befejeződik, ez az ablak bezárul, és a kicsomagolt mappa törlésre kerül"),
            'cs': ("Nelze zavřít při extrakci", "Aplikaci nelze zavřít, dokud nebude extrakce dokončena, jakmile bude dokončena, toto okno se zavře a extrahovaná složka bude smazána"),
            'sv': ("Kan inte stänga medan extraherar", "Programmet kan inte stängas förrän extraheringen är klar, så snart den är klar kommer det här fönstret att stängas och den extraherade mappen kommer att raderas"),
            'nl': ("Kan niet sluiten tijdens het extraheren", "De applicatie kan niet worden gesloten totdat het uitpakken is voltooid, zodra het is voltooid, wordt dit venster gesloten en wordt de uitgepakte map verwijderd"),
            'bg': ("Не може да се затвори по време на извличане", "Приложението не може да се затвори, докато извличането не приключи, веднъж приключено, този прозорец ще се затвори и извлечената папка ще бъде изтрита"),
            'fi': ("Ei voi sulkea purkamisen aikana", "Sovellusta ei voi sulkea, ennen kuin purkaminen on valmis, kun se on valmis, tämä ikkuna sulkeutuu ja purettu kansio poistetaan"),
            'da': ("Kan ikke lukke, mens der trækkes ud", "Programmet kan ikke lukkes, før udtrækningen er færdig, så snart den er færdig, lukkes dette vindue, og den udpakkede mappe slettes"),
            'no': ("Kan ikke lukke mens du pakker ut", "Programmet kan ikke lukkes før utpakkingen er ferdig, så snart den er ferdig, lukkes dette vinduet, og den utpakkede mappen blir slettet"),
            'el': ("Δεν μπορεί να κλείσει κατά την εξαγωγή", "Η εφαρμογή δεν μπορεί να κλείσει μέχρι να ολοκληρωθεί η εξαγωγή, μόλις ολοκληρωθεί, αυτό το παράθυρο θα κλείσει και ο εξαγόμενος φάκελος θα διαγραφεί"),
            'he': ("לא ניתן לסגור בעת חילוץ", "היישום לא יכול להיסגר עד שהחילוץ יסתיים, כשהוא יסתיים, החלון הזה ייסגר והתיקייה שחולצה תימחק"),
        },
    }

    @classmethod
    def getMessageText(cls,step, lang='es'):
        return cls.REVERSAL_TEXT[step[0]][lang]

    @classmethod
    def reverse(cls, step, temp_dir=None):
        if step == Step.DOWNLOADING or step == Step.EXTRACTING:
            shutil.rmtree(temp_dir)